title: Meteorological configuration
description: |-
  Configuration for meteorological input data handling in mHM.
  Meteorological weights can be used to disaggregate daily data to hourly values.
x-fortran-namelist: config_meteo
type: object
properties:
  read_meteo_weights:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Read meteorological weights
    description: |-
      Read meteorological weights from file instead of using fixed night ratios.
      The dimension for the weights are in FORTRAN-notation (rows, colums, months=12, hours=24)
      and in C-notation like in NetCDF: (hours=24, months=12, colums, rows).
  pre_weights_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Precipitation weights path
  pet_weights_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Potential evapotranspiration weights path
  temp_weights_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Surface downward shortwave radiation weights path
  ssrd_weights_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Surface downward shortwave radiation weights path
  strd_weights_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Surface downward longwave radiation weights path
  pre_weights_var:
    type: array
    items:
      type: string
      x-fortran-len: buf
      default: pre_weights
    x-fortran-shape: n_domains
    title: Precipitation weights variable name
  pet_weights_var:
    type: array
    items:
      type: string
      x-fortran-len: buf
      default: pet_weights
    x-fortran-shape: n_domains
    title: Potential evapotranspiration weights variable name
  temp_weights_var:
    type: array
    items:
      type: string
      x-fortran-len: buf
      default: tavg_weights
    x-fortran-shape: n_domains
    title: Average temperature weights variable name
  ssrd_weights_var:
    type: array
    items:
      type: string
      x-fortran-len: buf
      default: ssrd_weights
    x-fortran-shape: n_domains
    title: Surface downward shortwave radiation weights variable name
  strd_weights_var:
    type: array
    items:
      type: string
      x-fortran-len: buf
      default: strd_weights
    x-fortran-shape: n_domains
    title: Surface downward longwave radiation weights variable name
  frac_night_pre:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[0.46, 0.5, 0.52, 0.51, 0.48, 0.5, 0.49, 0.48, 0.52, 0.56, 0.5, 0.47]]
    title: Fraction of nightly precipitation
    description: |-
      Night ratio for precipitation (only if read_meteo_weights = .false.).
      Only night values (18h-5h) required because day values are the complement to 1.
      (array dimension 1: hour, dimension 2: domain)
  frac_night_pet:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]]
    title: Fraction of nightly potential evapotranspiration
    description: |-
      Night ratio for potential evapotranspiration (only if read_meteo_weights = .false.).
      Only night values (18h-5h) required because day values are the complement to 1.
      (array dimension 1: hour, dimension 2: domain)
  frac_night_temp:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[-0.76, -1.3, -1.88, -2.38, -2.72, -2.75, -2.74, -3.04, -2.44, -1.6, -0.94, -0.53]]
    title: Fraction of nightly temperature
    description: |-
      Additive night deviation for temperature (only if read_meteo_weights = .false.).
      Only night values (18h-5h) required because day values are the complement to 1.
      (array dimension 1: hour, dimension 2: domain)
  frac_night_ssrd:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
    title: Fraction of nightly surface downward shortwave radiation
    description: |-
      Night ratio for surface downward shortwave radiation (only if read_meteo_weights = .false.).
      Only night values (18h-5h) required because day values are the complement to 1.
      (array dimension 1: hour, dimension 2: domain)
  frac_night_strd:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45]]
    title: Fraction of nightly surface downward longwave radiation
    description: |-
      Night ratio for surface downward longwave radiation (only if read_meteo_weights = .false.).
      Only night values (18h-5h) required because day values are the complement to 1.
      (array dimension 1: hour, dimension 2: domain)
  share_frac:
    type: boolean
    default: true
    title: Share fractions between domains
    description: |-
      Share the same fraction values between all domains taking the values from the first domain.
      This only applies if `read_meteo_weights` is `.false.`.
      If set to false, different fraction values can be set for each domain.
