title: Optimization configuration
x-fortran-namelist: config_optimize
type: object
properties:
  optimize_restart:
    type: boolean
    default: false
    title: Restart optimization
    description: |-
      Optimization shall be restarted from ./mo_<opti_method>.restart file
  opti_method:
    type: integer
    x-fortran-kind: i4
    default: 1
    title: Optimization method
    description: |-
      Optimization method.
      (0) MCMC                (requires single-objective function)
      (1) DDS                 (requires single-objective function)
      (2) Simulated Annealing (requires single-objective function)
      (3) SCE                 (requires single-objective function)
  opti_function:
    type: integer
    x-fortran-kind: i4
    default: 10
    title: Objective function to be optimized
    description: |-
      Objective function to be optimized.
      (1)  SO: Q:   1.0 - NSE
      (2)  SO: Q:   1.0 - lnNSE
      (3)  SO: Q:   1.0 - 0.5*(NSE+lnNSE)
      (4)  SO: Q:  -1.0 * loglikelihood with trend removed from absolute errors and then lag(1)-autocorrelation removed
      (5)  SO: Q:   ((1-NSE)**6+(1-lnNSE)**6)**(1/6)
      (6)  SO: Q:   SSE
      (7)  SO: Q:  -1.0 * loglikelihood with trend removed from absolute errors
      (8)  SO: Q:  -1.0 * loglikelihood with trend removed from the relative errors and then lag(1)-autocorrelation removed
      (9)  SO: Q:   1.0 - KGE (Kling-Gupta efficiency measure)
      (10) SO: SM:  1.0 - KGE of catchment average soilmoisture
      (11) SO: SM:  1.0 - Pattern dissimilarity (PD) of spatially distributed soil moisture
      (12) SO: SM:  Sum of squared errors (SSE) of spatially distributed standard score (normalization) of soil moisture
      (13) SO: SM:  1.0 - average temporal correlation of spatially distributed soil moisture
      (14) SO: Q:   sum[((1.0-KGE_i)/nGauges)**6]**(1/6) - combination of KGE of every gauging station based on a power-6 norm
      (15) SO: Q + domain_avg_TWS: [1.0-KGE(Q)]*RMSE(domain_avg_TWS) - objective function using Q and domain average (standard score) TWS
      (16) (reserved) MO: Q: 1st objective: (1) = 1.0 - NSE; 2nd objective: (2) = 1.0 - lnNSE
      (17) SO: N:   1.0 - KGE of spatio-temporal neutron data, catchment-average
      (18) (reserved) MO: Q: 1st objective: 1.0 - lnNSE(Q_highflow) (95% percentile);
           2nd objective: 1.0 - lnNSE(Q_lowflow) (5% of data range)
      (19) (reserved) MO: Q: 1st objective: 1.0 - lnNSE(Q_highflow) (non-low flow);
           2nd objective: 1.0 - lnNSE(Q_lowflow) (5% of data range)
      (20) (reserved) MO: Q: 1st objective: absolute difference in FDC's low-segment volume;
           2nd objective: 1.0 - NSE of discharge of months DJF
      (21) (reserved) SO: Q: ((1.0-lnNSE(Q_highflow))**6 + (1.0-lnNSE(Q_lowflow))**6)**(1/6)
           where Q_highflow and Q_lowflow are calculated like in objective (19)
      (22-26) (reserved MC/JM/ST) please use the next number when implementing a new one
      (27) SO: ET:  1.0 - KGE of catchment average evapotranspiration
      (28) SO: Q + SM: weighted OF using SM (OF12) and Q (OF14) equally weighted
      (29) SO: Q + ET: weighted OF using ET (OF27) and Q (OF14) equally weighted
      (30) SO: Q + domain_avg_ET: [1.0-KGE(Q)]*RMSE(domain_avg_ET) - objective function using Q and domain average ET (standard score)
      (31) SO: Q:   1 - weighted NSE (NSE is weighted with observed discharge)
      (32) SO: objective_sse_boxcox
      (33) MO: objective_q_et_tws_kge_catchment_avg
      (34) SO: Q: (1 + |BFI_o - BFI_s|)(1 - KGE)
           BFI_s = mean_t(<q_2>) / mean_t(<q_total>)
           BFI_o = given in separate namelist per domain
           <.> is a spatial average
  iterations:
    type: integer
    x-fortran-kind: i4
    default: 7
    title: Number of iterations
  seed:
    type: integer
    x-fortran-kind: i4
    default: 1235876
    title: Seed
    description: |-
      Seed of random number generator.
      Default: -9: seed is obtained from system clock).
  dds_r:
    type: number
    x-fortran-kind: dp
    default: 0.2
    title: DDS perturbation rate
    description: |-
      Perturbation rate r for DDS algorithm.
  sa_temp:
    type: number
    x-fortran-kind: dp
    default: -9.0
    title: Initial Temperature
    description: |-
      Initial temperature for simulated annealing algorithm.
      Default -9: determined by algorithm of Ben-Ameur (2004).
  sce_ngs:
    type: integer
    x-fortran-kind: i4
    default: 2
    title: Number of SCE Complexes
  sce_npg:
    type: integer
    x-fortran-kind: i4
    default: -9
    title: Points per SCE Complex
    description: |-
      Points per SCE Complex.
      Default: -9 corresponds to 2n+1, with n being the number of SCE complexes.
  sce_nps:
    type: integer
    x-fortran-kind: i4
    default: -9
    title: Points per SCE Sub-Complex
    description: |-
      Points per SCE Sub-Complex.
      Default: -9 corresponds to n+1, with n being the number of SCE complexes.
  mcmc_opti:
    type: boolean
    default: false
    title: MCMC for optimisation
    description: |-
      If .true.: use MCMC for optimisation and estimation of parameter uncertainty.
      If .false.: use MCMC for estimation of parameter uncertainty.
  mcmc_error_params:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: 2
    default: [0.01, 0.6]
    title: Parameters of MCMC error model.
    description: |-
      Parameters of MCMC error model if mcmc_opti=.false.
      E.g. for opti_function=8: two parameters a and b: err = a + b*Q.
  BFI_calc:
    type: boolean
    default: true
    title: Calculate BFI from discharge time series with the Eckhardt filter
    description: |-
      Calculate BFI from discharge time series with the Eckhardt filter.
      This option **requires** one gauge per domain at the outlet of the basin.
      See: Eckhardt et al. (2008, doi: 10.1016/j.jhydrol.2008.01.005).
