title: Grid resolution configuration
description: |-
  Domain-indexed target resolutions for internally derived grids.
x-fortran-namelist: config_resolution
type: object
properties:
  hydro:
    type: array
    items:
      type: number
      x-fortran-kind: dp
      exclusiveMinimum: 0.0
    x-fortran-shape: n_domains
    title: Hydrological grid resolution
    examples: [[0.1]]
    description: |-
      Target resolution for deriving the hydrological grid from the morphological grid.
      Unit is degrees for geographic coordinate systems and meters otherwise, as determined from the morphological grid.
  route:
    type: array
    items:
      type: number
      x-fortran-kind: dp
      exclusiveMinimum: 0.0
    x-fortran-shape: n_domains
    title: Routing grid resolution
    examples: [[0.5]]
    description: |-
      Target resolution for deriving the routing grid from the morphological grid.
      Unit is degrees for geographic coordinate systems and meters otherwise, as determined from the morphological grid.
