title: Observations configuration
description: Configuration for observation input data in mHM.
x-fortran-namelist: config_observations
type: object
properties:
  sm_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Soil moisture data path
    description: |-
      Path to soil moisture input data.
      Expected variable name: "sm".
  neutrons_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Neutron data path
    description: |-
      Path to neutron input data.
      Expected variable name: "neutrons".
  et_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Evapotranspiration data path
    description: |-
      Path to evapotranspiration input data.
      Expected variable name: "et".
  tws_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Domain average TWS path
    description: |-
      Path to total water storage input data.
      Expected variable name: "twsa".
  BFI_obs:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: n_domains
    title: Baseflow index per domain
    description: |-
      Baseflow index per domain. Only needed if not calculated (BFI_calc = .false.).
      You can overwrite single BFI values to not calculate them internally (if BFI_calc = .true.).
  sm_horizons:
    type: integer
    x-fortran-kind: i4
    title: Number of mHM soil moisture horizons
    description: |-
      Number of mHM soil moisture horizons for which the soil moisture input is representative for (counted top to down).
  sm_time_step:
    type: integer
    x-fortran-kind: i4
    title: Time step of soil moisture
    description: |-
      Time step of soil moisture input data.
      - -1 : daily
      - -2 : monthly
      - -3 : yearly
  et_time_step:
    type: integer
    x-fortran-kind: i4
    title: Time step of evapotranspiration
    description: |-
      Time step of evapotranspiration input data.
      - -1 : daily
      - -2 : monthly
      - -3 : yearly
  tws_time_step:
    type: integer
    x-fortran-kind: i4
    title: Time step of total water storage
    description: |-
      Time step of total water storage input data.
      - -1 : daily
      - -2 : monthly
      - -3 : yearly
