title: mHM model configuration
description: |-
  Configuration for the mHM model setup.
x-fortran-namelist: config_mhm
type: object
properties:
  output_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Output path
    examples: [["mhm_output.nc"]]
  read_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Read restart
  restart_input_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Restart input path
    examples: [["mhm_restart_in.nc"]]
  write_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Write restart
  restart_output_path:
    type: array
    items:
      type: string
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Restart output path
    examples: [["mhm_restart_out.nc"]]
  evap_coeff:
    type: array
    items:
      type: number
      x-fortran-kind: dp
    x-fortran-shape: [12, n_domains]
    examples: [[1.3, 1.2, 0.72, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5]]
    title: Evaporation coefficients
    description: |-
      Monthly free pan evaporation coefficients for free-water surfaces.
      (array dimension 1: month, dimension 2: domain)
  share_evap_coeff:
    type: boolean
    default: true
    title: Share evaporation coefficients between domains
    description: |-
      Share the same evaporation coefficient values between all domains taking the values from the first domain.
      If set to false, different evaporation coefficient values can be set for each domain.
