title: mRM configuration
description: Configuration for the multi-scale routing model (mRM) in mHM.
x-fortran-namelist: config_mrm
type: object
properties:
  river_net_order_root_based:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Flag for root based river network ordering.
    description: |-
      Flag to indicate if the river network is ordered in root based order.
      If false, the ordering is leaf based.
      Root based ordering results in more equal distributed level sizes for parallelization.
      Leaf based ordering has huge levels of nodes at the headwaters, which can lead to load balancing issues.
    examples: [[true]]
  river_net_omp_level_min:
    type: array
    items:
      type: integer
      x-fortran-kind: i4
      default: -1
      minimum: -1
    x-fortran-shape: n_domains
    title: Minimum level size for OpenMP parallelization.
    description: |-
      Minimum level size in the river network where OpenMP parallelization starts.
      Levels smaller than this size are always computed serially.
      This can be used to avoid parallelization overhead for small levels of the river network,
      especially when ordering is leaf based.

      Special values are:
      - -1 : lets the model choose a default based on the number of threads.
      -  1 : forces parallelization on all levels.
      -  0 : disables parallelization.
      By default: threads * 8 (indicated by -1)
    examples: [[100]]
  max_route_step:
    type: array
    items:
      type: integer
      x-fortran-kind: i4
      enum: [60, 120, 180, 240, 300, 360, 600, 720, 900, 1200, 1800, 3600, 7200, 10800, 14400, 21600, 28800, 43200, 86400]
      default: 86400
    x-fortran-shape: n_domains
    title: Maximum routing time step in seconds.
    description: |-
      Maximum allowed time step for the routing model in seconds.
      This parameter can be used to limit the time step in case of very large CFL time steps
      due to very low flow velocities.
      This is useful in coupling scenarios to match the time step of other models.
      If routing time step is smaller than the model time step, multiple routing steps are performed per model time step.
      Valid values range from 1 minute (60s) to 1 day (86400s).
      Value needs to be a divisor of 3600 or a multiple of 3600 and a divisor of 86400.
    examples: [[3600]]
  scc_gauges_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Path for SCC gauges NetCDF file.
    examples: [["scc_gauges.nc"]]
  output_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Path for output file.
    examples: [["mrm_output.nc"]]
  output_node_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Path for node based output file.
    examples: [["mrm_node_output.nc"]]
  read_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Read restart
  read_restart_fluxes:
    type: array
    items:
      type: boolean
      default: true
    x-fortran-shape: n_domains
    title: Read restart fluxes
  restart_input_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Restart input path
    examples: [["mrm_restart_in.nc"]]
  write_restart:
    type: array
    items:
      type: boolean
      default: false
    x-fortran-shape: n_domains
    title: Write restart
  restart_output_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Restart output path
    examples: [["mrm_restart_out.nc"]]
  diagnostics_path:
    type: array
    items:
      type: string
      format: file-path
      x-fortran-len: buf
    x-fortran-shape: n_domains
    title: Diagnostics output path
    description: |-
      Path for diagnostics output file containing information about the river upscaling and SCC.
    examples: [["mrm_diagnostics.nc"]]
